[package]
name = "proxy"
version = "0.2.3"
edition = "2024"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[lints.rust]
unsafe_code = "forbid"
# while developing, allow dead code and unused imports/variables
dead_code = { level = "allow", priority = -1 }
unused = { level = "allow", priority = -1 }

[dependencies]
# Async
async-trait = "0.1.92"
tokio = { version = "1.53.1", features = ["full"] }

# Arc
arc-swap = "1.9.2"

# Certs
# used Ring as backend for default
rcgen = { version = "0.14.8", features = ["default"] }
# match the backed from rcgen
instant-acme = { version = "0.8.5", default-features = false, features = [
   "ring",
   "rcgen",
   "hyper-rustls",
] }
rustls = "0.23.43"


# TOML
toml = "1.1.4"

# Json
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

# Others
thiserror = "2.0.20"
chrono = { version = "0.4.45", features = ["serde"] }

# HTTP
http = "1.5.0"
pingora = { version = "0.8.1", features = ["proxy", "boringssl"] }

# HTTP Client
reqwest = { version = "0.13.4", features = ["json"] }
