[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[lints.rust]
unsafe_code = "forbid"
# while developing, allow dead code and unused imports/variables
dead_code = { level = "allow", priority = -1 }
unused = { level = "allow", priority = -1 }

[dependencies]
# Async
async-trait = "0.1.89"
tokio = { version = "1.52.3", features = ["full"] }

# Arc
arc-swap = "1.9.1"

# Certs
# used Ring as backend for default
rcgen = { version = "0.14.8", features = ["default"] }
# match the backed from rcgen
instant-acme = { version = "0.8.5", features = ["rcgen"] }

# TOML
toml = "1.1.2"

# Json
serde = { version = "1.0.228", features = ["derive"] }

# Others
thiserror = "2.0.18"
chrono = { version = "0.4.45", features = ["serde"] }

# HTTP
http = "1.4.1"
pingora = { version = "0.8.1", features = ["proxy", "boringssl"] }
